### ISSUE TITLE
ReferenceError: crypto is not defined

### ISSUE THREAD

**Issue by Xceron** [Explosion-Scratch/claude-unofficial-api#1]
Hey!

When I try to run claude cli, I get the following error:

```
ReferenceError: crypto is not defined
    at Claude.startConversation (file:///C:/Users/myUser/AppData/Roaming/npm/node_modules/claude-cli/node_modules/claude-ai/index.js:36:23)
    at main (file:///C:/Users/myUser/AppData/Roaming/npm/node_modules/claude-cli/index.js:196:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I am not really familiar with node, but it seems like an import is missing in the main index.js ([Link](https://github.com/Explosion-Scratch/claude-unofficial-api/blob/main/index.js)). 

More information:
OS: Windows 11
node version: v18.16.1
npm version: 9.8.0

**Comment by Explosion-Scratch** [comment]
Try it now! =)

**Comment by Xceron** [comment]
Works perfect, what a quick fix! Thank you very much :)
