### ISSUE TITLE
Error: Conversation ID required

### ISSUE THREAD

**Issue by BelugaWhale** [Explosion-Scratch/claude-unofficial-api#13]
ERROR with require:

```
$ node claude.js
E:\repositories\Claude_test\claude.js:2
const Claude = require('claude-ai');
               ^

Error [ERR_REQUIRE_ESM]: require() of ES Module E:\repositories\Claude_test\node_modules\claude-ai\index.js from E:\repositories\Claude_test\claude.js not supported.
Instead change the require of index.js in E:\repositories\Claude_test\claude.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> ←[90m(E:\repositories\Claude_test\←[39mclaude.js:2:16←[90m)←[39m {
  code: ←[32m'ERR_REQUIRE_ESM'←[39m
}
```

Fixed with this:     `const Claude = (await import('claude-ai')).default;`

NEXT ERROR:

```
$ node claude.js
Error occurred:  Error: Conversation ID required
    at new Conversation (file:///E:/repositories/Claude_test/node_modules/claude-ai/index.js:198:19)
    at Claude.startConversation (file:///E:/repositories/Claude_test/node_modules/claude-ai/index.js:112:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runTest (E:\repositories\Claude_test\claude.js:12:26)
```

CODE:
```
async function runTest() {
  try {
    // Dynamically import the Claude library
    const Claude = (await import('claude-ai')).default;

    // Initialize a new Claude instance with your session key
    const claude = new Claude({
      sessionKey: 'sk-N-C2olHC...3cFZuA-rHytqgAA'  // replace this with your actual session key
    });

    // Start a new conversation
    const conversation = await claude.startConversation('Hello Claude!');

    // Send a follow-up message
    await conversation.sendMessage('How are you today?');

    // Fetch and log conversation details
    const info = await conversation.getInfo();
    console.log(info);
  } catch (error) {
    console.error('Error occurred: ', error);
  }
}

runTest();
```

**Comment by Explosion-Scratch** [comment]
You didn't call `await claude.init()`

**Comment by Explosion-Scratch** [comment]
I've just added JSDocs which have many references to .init, I'll add it to the docs once I get rid of the headache I've gotten from coding all day

**Comment by Explosion-Scratch** [comment]
> Take it easy king

thx lol, maybe some coffee and the great outdoors, then some delightful act prep
