### ISSUE TITLE
error with uploadFile(file)

### ISSUE THREAD

**Issue by wrhsd1** [Explosion-Scratch/claude-unofficial-api#33]
It seems that you encountered an error when using the 
`const uploadedFile = await claude.uploadFile(file);`

function via the API. The error message indicates the following:

```
file:///root/claude-unofficial-api/claude-unofficial-api/index.js:601
    const buf = await file.arrayBuffer();
                           ^

TypeError: file.arrayBuffer is not a function
    at readAsText (file:///root/claude-unofficial-api/claude-unofficial-api/index.js:601:28)
    at Claude.uploadFile (file:///root/claude-unofficial-api/claude-unofficial-api/index.js:310:43)
    at main (/root/claude-unofficial-api/claude-unofficial-api/2.cjs:22:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.0
```
Is there a problem?

**Comment by Explosion-Scratch** [comment]
Is your file a js [File](https://developer.mozilla.org/en-US/docs/Web/API/File) object?

**Comment by Explosion-Scratch** [comment]
If you're trying to upload a file from your file system please use the [`mime-types`](https://www.npmjs.com/package/mime-types) package from NPM and use this method:
```js
import mime from "mime-types"
function uploadFile(claude, filename){
   const file = new File([readFileSync(filename)], filename.split('/').slice(-1)[0], { type: mime.lookup(filename) });
   return claude.uploadFile(file);
}
```

**Comment by wrhsd1** [comment]
yes i will try again and thanks for your reply!

**Comment by Explosion-Scratch** [comment]
You also need to `import {readFileSync} from "fs"` btw

**Comment by wrhsd1** [comment]
Now everything is settled, thank you.
