### ISSUE TITLE
code: 'UND_ERR_CONNECT_TIMEOUT'

### ISSUE THREAD

**Issue by HowieHwong** [Explosion-Scratch/claude-unofficial-api#35]
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Claude.getOrganizations (file:///Users/howiehwong/Desktop/%E7%AC%AC%E5%9B%9B%E6%96%B9%E6%94%AF%E4%BB%98/yolov5/datasets/claude-unofficial-api-main/index.js:178:26)
    at async Claude.init (file:///Users/howiehwong/Desktop/%E7%AC%AC%E5%9B%9B%E6%96%B9%E6%94%AF%E4%BB%98/yolov5/datasets/claude-unofficial-api-main/index.js:148:31)
    at async file:///Users/howiehwong/Desktop/%E7%AC%AC%E5%9B%9B%E6%96%B9%E6%94%AF%E4%BB%98/yolov5/datasets/claude-unofficial-api-main/index.js:744:1 {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8422:28)
      at node:internal/deps/undici/undici:8380:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8411:13)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

Here is my code added at the end of the file `index.js`
const claude = new Claude({
  sessionKey: 'sk-ant-sid01-*********************'
});

await claude.init();

const conversation = await claude.startConversation('Hello Claude!');

await conversation.sendMessage('How are you today?');

**Comment by Explosion-Scratch** [comment]
Your internet connection likely glitched or Claude blocked you somehow, either way, not something I can fix with the library.
