### ISSUE TITLE
Error: Conversation ID required

### ISSUE THREAD

**Issue by Vallent16** [Explosion-Scratch/claude-unofficial-api#6]
Hey, I'm getting this error:

            throw new Error('Conversation ID required');
                  ^
Error: Conversation ID required
    at new Conversation (file:///C:/Documents/Github/claude-unofficial-api/node_modules/claude-ai/index.js:142:19)
    at Claude.startConversation (file:///C://Documents/Github/claude-unofficial-api/node_modules/claude-ai/index.js:62:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startConversation (file:///C:/Documents/Github/claude-unofficial-api/test2.mjs:9:24)
    
    For reference, this is my code:
    
    import { Claude } from 'claude-ai';

const startConversation = async () => {
  const claude = new Claude({
    sessionKey: '[my key]'
  });

  const conversation = await claude.startConversation('Hello Claude!');
  console.log(conversation);
  const response = await conversation.sendMessage('How are you today?');
  console.log(response);
};

startConversation();

**Comment by Jarvan-via** [comment]
claude AI had changed reponse, now not work

**Comment by Explosion-Scratch** [comment]
You forgot `await claude.init()`
